DROP TABLE IF EXISTS EVENT_PUBLICATION;

CREATE TABLE EVENT_PUBLICATION
(
    ID               UUID PRIMARY KEY,
    COMPLETION_DATE  date,
    EVENT_TYPE       varchar(1024),
    LISTENER_ID      varchar(1024),
    PUBLICATION_DATE date,
    SERIALIZED_EVENT varchar(1024)
);